### ISSUE TITLE
Desktop data.zip is missing

### ISSUE THREAD

**Issue by JayFoxRox** [TerryCavanagh/VVVVVV#5]
The mobile version README.md links to https://thelettervsixtim.es/opensource/vvvvvv%20mobile%20data%20folder.zip
The desktop version doesn't seem to have such a file. This leads to the following crash:

```
[New Thread 0x7fffeef91700 (LWP 165545)]
double free or corruption (out)

Thread 1 "vvvvvv.x86_64" received signal SIGABRT, Aborted.
0x00007ffff761ff25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff761ff25 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff7609897 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff7663258 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff766a77a in  () at /usr/lib/libc.so.6
#4  0x00007ffff766c5d0 in _int_free () at /usr/lib/libc.so.6
#5  0x00005555555db1d9 in FILESYSTEM_freeMemory(unsigned char**) (mem=0x7fffffff8be0) at /home/fox/Data/Projects/VVVVVV/desktop_version/src/FileSystemUtils.cpp:116
#6  0x0000555555826bed in SoundTrack::SoundTrack(char const*) (this=0x7fffffff8c50, fileName=0x555555947f8e "sounds/jump.wav") at /home/fox/Data/Projects/VVVVVV/desktop_version/src/SoundSystem.cpp:36
#7  0x00005555556ad3e2 in musicclass::musicclass() (this=0x7fffffffaf00) at /home/fox/Data/Projects/VVVVVV/desktop_version/src/Music.cpp:8
#8  0x00005555558ebade in main(int, char**) (argc=1, argv=0x7fffffffe888) at /home/fox/Data/Projects/VVVVVV/desktop_version/src/main.cpp:98
(gdb) 
```

I'm able to work around this issue by this patch:

```diff
diff --git a/desktop_version/src/FileSystemUtils.cpp b/desktop_version/src/FileSystemUtils.cpp
index c2f936c..f664bdb 100644
--- a/desktop_version/src/FileSystemUtils.cpp
+++ b/desktop_version/src/FileSystemUtils.cpp
@@ -75,7 +75,8 @@ void FILESYSTEM_init(char *argvZero)
 #else
        strcpy(output, "data.zip");
 #endif
-       PHYSFS_mount(output, NULL, 1);
+       PHYSFS_mount("data", NULL, 1);
 }
```

You then have to extract the mobile game versions data folder to your binary path, and also convert some files manually. Audio, however, won't work.

**Comment by flibitijibibo** [comment]
Duplicate of #3, basically you need to grab it from your purchased copy (or from Make and Play).
